### ISSUE TITLE
Using the module on the frontend (webpack) causes warnings

### ISSUE THREAD

**Issue by aaronschwartz** [YStrauch/swagger-object-validator#3]
I love the idea of this library.

I'm trying to use it client side to validate my objects against the swagger definitions before posting them to the server.

The first issue I ran into is this error:
```
ERROR in ./~/swagger-object-validator/lib/helpers/loader.js
Module not found: Error: Can't resolve 'fs' in '/project/node_modules/swagger-object-validator/lib/helpers'
 @ ./~/swagger-object-validator/lib/helpers/loader.js 3:13-26
```

I got rid of it by including the following in my webpack config:
```
    node: {
      fs: 'empty'
    },
```
I would rather not have to add that though.

The second issue is that now that I have it running I still get the following warning both from my webpack console and in my javascript console:
```
WARNING in ./~/swagger-object-validator/lib/helpers/loader.js
105:57-70 Critical dependency: the request of a dependency is an expression
```

I'm using `webpack@2.6.1` and `browser-sync@2.18.12`

Let me know if you want to see any more of my configuration.

**Comment by YStrauch** [comment]
Hallo Aaron,

I am sorry to tell you that the focus of this module is solely backend validation. I honestly cannot think of any reason why a module that verifies data between a backend and a frontend should be used in the frontend. On the one hand it is too slow to be used client side (think of mobile devices), on the other hand it would produce code that you surely won't use in production.

I cannot remove the dependency to fs since swagger explicitly uses $ref (JSON draft) in order to split a spec into multiple files, and without fs this basic feature would be unavailable on backend.

Can you please tell me the reasons for why you want to use the module in frontend context?

**Comment by aaronschwartz** [comment]
Our product has a website running on a piece of hardware.

The frontend is React and it is calling a REST(ish) API written in c++.

The API is documented using Swagger but we are not using it to generate either side.

I want to use the Swagger documentation as the source of truth for validation purposes. I want to validate forms against the swagger json schema. For example, I want to validate min/max of certain values before they get submitted. I don't want those min/max constants hardcoded in my web app. 

The swagger yaml file will be downloaded from the server once on page load.

My use case is frontend form validation using the Swagger schema. Playing around with your library it does seem possible. For efficiency I was going to only request the schema and parse it/create the validator once on page load and then store it in react's context or some other global scope.

**Comment by YStrauch** [comment]
I had a similar task and decided not to compromise my frontend code with a validator that is useless in production mode, so I created a proxy server with express that validates data. If you want to use it in frontend it is your choice.

Here is what i can do for you: I removed other warnings due to a rather hacky JSON import script, and I throw an error if someone tries to use fs in frontend.

What i couldn't do is getting rid of the warning. It is correct that webpack warns you about not being able to pack a module into your bundle. And I cannot remove the module. I've seen other projects with the same issue and they all use the fix that you already mentioned -

```
node: {
  fs: 'empty'
},
```

**Comment by aaronschwartz** [comment]
Thanks. That's awesome. 

Can I ask what you mean by useless in production mode? I am trying to find other solutions as well still.

I think creating a proxy server might be overkill for our product. Our product hardware is probably slower than our client's computers (and may not have full internet access). Also did that mean that you had to make a server request every time you wanted to validate a form?

**Comment by YStrauch** [comment]
Oh I misread your comment, forget about production.

Please don't forget that you shouldn't rely on frontend validation only, you will need to validate backend side.
