### ISSUE TITLE
Null value for non-required fields triggers error

### ISSUE THREAD

**Issue by ethanchiddicks** [YStrauch/swagger-object-validator#8]
When a model has a non-required field, and that value is set to null, this library still flags an error. For example:
```
var swaggerValidator = require('swagger-object-validator');
var validator = new swaggerValidator.Handler('https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml');

var pet = {
  id: 3942394023,
  name: 'Pippin',
  tag: null
}

validator.validateModel(pet, 'Pet', function (err, result) {
  console.log(result.humanReadable()); //Type mismatch: - At Pet/tag - Should be: "string" - Is: "null"
});
```
If you leave the tag field out entirely, the validation passes. I'd like to be able to set an option to allow non-required field values to null.

**Comment by YStrauch** [comment]
Yeah this is the old _null_ versus _undefined_ discussion. One of the architectural things in JavaScript that I don't like.

Furthermore from a data load perspective it us unnecessary to send intentional empty values, since there is no benefit (empty optional properties are empty...) and it only increases traffic.
I have too look up what the swagger spec says about _null_ versus _undefined_ and then evaluate if _null_ is a valid state for optional properties.

Until this clears up, you can use _undefined_  in your model as a workaround.

**Comment by WesleydeSouza** [comment]
Swagger 3 defines `nullable` as part of the [Schema Object possible properties](https://swagger.io/specification/#schemaObject).

There is abundant usage of this value on Swagger 2 around (including support from other validation libraries), by using `x-nullable`:

```yaml
readyOn:
  type: string
  format: date-time
  x-nullable: true
```

I'm considering forking this and implementing it, since my current use case needs this (the API does return `null` and it's out of our control).
